#
# Project: GAL 2014
# Author: Alena Chernikava
# Date: 30.11.2014
#

NAME=egervarypar
CC=gcc
CFLAGS=-std=c99  -pedantic -Wall -W -g -lpthread 

all: $(NAME).c
	$(CC) $(CFLAGS) $(NAME).c -o $(NAME)

clean:
	rm $(NAME)
