#
# Project: GAL 2014
# Author: Vendula Poncova
# Date: 13.11.2014
#

NAME=matching
CC=gcc
CFLAGS=-std=c99  -pedantic -Wall -W -g -O3

all: $(NAME).c
	$(CC) $(CFLAGS) $(NAME).c -o $(NAME) -lpthread

clean:
	rm $(NAME)
